# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-01 10:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostel',
            name='mess1_maharaj_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='hostel',
            name='mess2_maharaj_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='hostel',
            name='mess3_maharaj_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='hostel',
            name='number_of_students',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
