# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-01 14:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0002_auto_20181201_1037'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostel',
            name='HEC',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='hostel',
            name='canteen_menu',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='hostel',
            name='care_takers',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='hostel',
            name='duties_of_hec',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='hostel',
            name='maintainance_workers',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='hostel',
            name='mess_bill_link',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='hostel',
            name='student_list',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='hostel',
            name='wardens',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
