# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-01 14:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0003_auto_20181201_1411'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notifcation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(blank=True, max_length=2000, null=True)),
                ('message', models.TextField()),
                ('time_stamp', models.DateTimeField(default=datetime.datetime(2018, 12, 1, 14, 53, 8, 724454))),
                ('hostel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Student.Hostel')),
            ],
        ),
    ]
