# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-02 17:53
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Student', '0008_auto_20181202_0612'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grievance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, max_length=200, verbose_name='Subject')),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime(2018, 12, 2, 17, 53, 4, 738710))),
                ('description', models.CharField(blank=True, max_length=1000, verbose_name='Description')),
                ('expected_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='GrievanceCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('authority', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='notifcation',
            name='time_stamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 2, 17, 53, 4, 736214)),
        ),
        migrations.AddField(
            model_name='grievance',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Student.GrievanceCategory'),
        ),
        migrations.AddField(
            model_name='grievance',
            name='hostel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Student.Hostel'),
        ),
        migrations.AddField(
            model_name='grievance',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
