# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-03 11:48
from __future__ import unicode_literals

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0010_auto_20181203_0745'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostelAllotment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('start_room', models.PositiveIntegerField(default=1)),
                ('end_room', models.PositiveIntegerField(default=1)),
                ('per_room', models.PositiveIntegerField(default=2, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)])),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Student.Branch')),
                ('hostel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Student.Hostel')),
            ],
        ),
        migrations.CreateModel(
            name='Roominfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_no', models.IntegerField()),
                ('is_filled', models.BooleanField(default=False)),
                ('in_queue', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('hostel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Student.Hostel')),
                ('member1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mem1', to='Student.Profile')),
                ('member2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mem2', to='Student.Profile')),
                ('member3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mem3', to='Student.Profile')),
            ],
        ),
        migrations.AlterField(
            model_name='grievance',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 12, 3, 11, 48, 17, 9866)),
        ),
        migrations.AlterField(
            model_name='notifcation',
            name='time_stamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 3, 11, 48, 17, 7358)),
        ),
    ]
