# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-03 12:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0011_auto_20181203_1148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roominfo',
            name='hostel',
        ),
        migrations.AddField(
            model_name='roominfo',
            name='scheme',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Student.HostelAllotment'),
        ),
        migrations.AlterField(
            model_name='grievance',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 12, 3, 12, 38, 14, 819313)),
        ),
        migrations.AlterField(
            model_name='notifcation',
            name='time_stamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 3, 12, 38, 14, 816737)),
        ),
    ]
