# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-03 15:33
from __future__ import unicode_literals

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0012_auto_20181203_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='year',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='grievance',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 12, 3, 15, 33, 4, 58838)),
        ),
        migrations.AlterField(
            model_name='notifcation',
            name='time_stamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 3, 15, 33, 4, 56178)),
        ),
    ]
