# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-03 16:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0013_auto_20181203_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='roominfo',
            name='count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='grievance',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 12, 3, 16, 31, 53, 141518)),
        ),
        migrations.AlterField(
            model_name='notifcation',
            name='time_stamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 3, 16, 31, 53, 138812)),
        ),
    ]
