# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-16 06:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0017_auto_20181215_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grievance',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 12, 16, 6, 24, 25, 100828)),
        ),
        migrations.AlterField(
            model_name='notifcation',
            name='time_stamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 16, 6, 24, 25, 98270)),
        ),
        migrations.AlterField(
            model_name='roominfo',
            name='member1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mem1', to='Student.Profile'),
        ),
        migrations.AlterField(
            model_name='roominfo',
            name='member2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mem2', to='Student.Profile'),
        ),
        migrations.AlterField(
            model_name='roominfo',
            name='member3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mem3', to='Student.Profile'),
        ),
    ]
