# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-03 14:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0018_auto_20181216_0624'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostel',
            name='flag_image',
            field=models.ImageField(null=True, upload_to='hostel_images'),
        ),
        migrations.AlterField(
            model_name='grievance',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 1, 3, 14, 48, 38, 573056)),
        ),
        migrations.AlterField(
            model_name='notifcation',
            name='time_stamp',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 3, 14, 48, 38, 570401)),
        ),
    ]
