# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-23 09:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0019_auto_20190103_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='grievance',
            name='comment',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='grievance',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 1, 23, 9, 55, 43, 956865)),
        ),
        migrations.AlterField(
            model_name='notifcation',
            name='time_stamp',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 23, 9, 55, 43, 954281)),
        ),
    ]
