# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-03-03 19:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0020_auto_20190123_0955'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('post', models.CharField(max_length=150)),
                ('contact_no', models.PositiveIntegerField(default=0)),
                ('emailid', models.CharField(max_length=150)),
                ('hostel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Student.Hostel')),
            ],
        ),
        migrations.AlterField(
            model_name='grievance',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 3, 3, 19, 42, 51, 559446)),
        ),
        migrations.AlterField(
            model_name='notifcation',
            name='time_stamp',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 3, 19, 42, 51, 556901)),
        ),
    ]
