# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-03-03 19:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0021_auto_20190303_1942'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='profilepic',
            field=models.ImageField(null=True, upload_to='staff_images'),
        ),
        migrations.AlterField(
            model_name='grievance',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 3, 3, 19, 45, 45, 680403)),
        ),
        migrations.AlterField(
            model_name='notifcation',
            name='time_stamp',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 3, 19, 45, 45, 677625)),
        ),
    ]
