# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-03-04 07:39
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Student', '0022_auto_20190303_1945'),
    ]

    operations = [
        migrations.CreateModel(
            name='LostFound',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.BooleanField(default=False)),
                ('date', models.DateField(blank=True, default=datetime.datetime(2019, 3, 4, 7, 39, 24, 12499))),
                ('subject', models.CharField(max_length=100)),
                ('item_info', models.CharField(max_length=500)),
                ('location_info', models.CharField(max_length=500)),
                ('item_image1', models.ImageField(upload_to='lostfound_images')),
                ('item_image2', models.ImageField(upload_to='lostfound_images')),
                ('item_image3', models.ImageField(upload_to='lostfound_images')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='grievance',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 3, 4, 7, 39, 24, 9309)),
        ),
        migrations.AlterField(
            model_name='notifcation',
            name='time_stamp',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 4, 7, 39, 24, 6756)),
        ),
    ]
