# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-03-04 07:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0023_auto_20190304_0739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grievance',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 3, 4, 7, 41, 9, 669087)),
        ),
        migrations.AlterField(
            model_name='lostfound',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2019, 3, 4, 7, 41, 9, 672303)),
        ),
        migrations.AlterField(
            model_name='lostfound',
            name='item_info',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='lostfound',
            name='subject',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='notifcation',
            name='time_stamp',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 4, 7, 41, 9, 666513)),
        ),
    ]
