# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-03-04 07:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0024_auto_20190304_0741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grievance',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 3, 4, 7, 42, 15, 187418)),
        ),
        migrations.AlterField(
            model_name='lostfound',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2019, 3, 4, 7, 42, 15, 190754)),
        ),
        migrations.AlterField(
            model_name='lostfound',
            name='item_image1',
            field=models.ImageField(null=True, upload_to='lostfound_images'),
        ),
        migrations.AlterField(
            model_name='lostfound',
            name='item_image2',
            field=models.ImageField(null=True, upload_to='lostfound_images'),
        ),
        migrations.AlterField(
            model_name='lostfound',
            name='item_image3',
            field=models.ImageField(null=True, upload_to='lostfound_images'),
        ),
        migrations.AlterField(
            model_name='notifcation',
            name='time_stamp',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 4, 7, 42, 15, 184867)),
        ),
    ]
