# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-03-04 07:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0025_auto_20190304_0742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grievance',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 3, 4, 7, 46, 52, 208620)),
        ),
        migrations.AlterField(
            model_name='lostfound',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2019, 3, 4, 7, 46, 52, 211800)),
        ),
        migrations.AlterField(
            model_name='lostfound',
            name='location_info',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='lostfound',
            name='subject',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='lostfound',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Student.Profile'),
        ),
        migrations.AlterField(
            model_name='notifcation',
            name='time_stamp',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 4, 7, 46, 52, 206055)),
        ),
    ]
