# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-10 14:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0026_auto_20190304_0746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grievance',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 4, 10, 14, 23, 55, 832577)),
        ),
        migrations.AlterField(
            model_name='lostfound',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2019, 4, 10, 14, 23, 55, 838592)),
        ),
        migrations.AlterField(
            model_name='notifcation',
            name='time_stamp',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 10, 14, 23, 55, 828969)),
        ),
    ]
