# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-14 08:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0027_auto_20190410_1423'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contributor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('imageurl', models.CharField(max_length=300)),
                ('rollno', models.CharField(max_length=15)),
                ('branch', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=150)),
                ('github', models.CharField(max_length=150)),
                ('linkedin', models.CharField(max_length=150)),
            ],
        ),
        migrations.AlterField(
            model_name='grievance',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 4, 14, 8, 56, 44, 955588)),
        ),
        migrations.AlterField(
            model_name='lostfound',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2019, 4, 14, 8, 56, 44, 961992)),
        ),
        migrations.AlterField(
            model_name='notifcation',
            name='time_stamp',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 14, 8, 56, 44, 951867)),
        ),
    ]
