# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-14 09:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0030_auto_20190414_0902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributor',
            name='rollno',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='grievance',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 4, 14, 9, 10, 10, 614511)),
        ),
        migrations.AlterField(
            model_name='lostfound',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2019, 4, 14, 9, 10, 10, 621163)),
        ),
        migrations.AlterField(
            model_name='notifcation',
            name='time_stamp',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 14, 9, 10, 10, 609953)),
        ),
    ]
