# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-14 09:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0032_auto_20190414_0913'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='B.tech', max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='contributor',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Student.Branch'),
        ),
        migrations.AlterField(
            model_name='grievance',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 4, 14, 9, 50, 27, 680291)),
        ),
        migrations.AlterField(
            model_name='lostfound',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2019, 4, 14, 9, 50, 27, 686217)),
        ),
        migrations.AlterField(
            model_name='notifcation',
            name='time_stamp',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 14, 9, 50, 27, 675268)),
        ),
        migrations.AddField(
            model_name='contributor',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Student.Course'),
        ),
    ]
